blank_issues_enabled: false
contact_links:
  - name: 📚 Development Documentation
    url: https://github.com/srearl/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Learn how to set up and work with the codebase
  - name: 💬 Discussion Forum
    url: https://github.com/srearl/skills-expand-your-team-with-copilot/discussions
    about: Ask questions and discuss ideas with the community