name: 🎨 UI/Design Improvement
description: Suggest improvements to the website's appearance, layout, or user experience
title: "[UI/UX] "
labels: ["ui/ux", "enhancement", "teacher-request"]
body:
  - type: markdown
    attributes:
      value: |
        Want to make the website easier to use or better looking? Use this form to suggest design improvements.

  - type: dropdown
    id: improvement-type
    attributes:
      label: What type of improvement are you suggesting?
      options:
        - Make text larger or easier to read
        - Improve colors or visual design
        - Better organization/layout of information
        - Make buttons or links more obvious
        - Improve mobile/tablet experience
        - Make navigation easier
        - Reduce clutter or simplify interface
        - Add visual elements (icons, images, etc.)
        - Other design improvement
    validations:
      required: true

  - type: textarea
    id: current-issue
    attributes:
      label: What's the current problem or challenge?
      description: Describe what makes the current design difficult or confusing.
      placeholder: |
        Example: "The activity cards are too small and hard to read on tablets"
        or "Students can't easily find the search box"
        or "The signup button is not obvious enough"
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: What would you like to see instead?
      description: Describe your ideal solution or improvement.
      placeholder: |
        Example: "Make the activity cards bigger with larger text"
        or "Move the search box to the top of the page"
        or "Make the signup button a bright color that stands out"
    validations:
      required: true

  - type: dropdown
    id: affects-who
    attributes:
      label: Who would benefit from this improvement?
      options:
        - Students (easier for them to find and sign up for activities)
        - Teachers (easier to manage or review activities)
        - Both students and teachers
        - Parents/guardians viewing the site
        - Everyone who uses the website
    validations:
      required: true

  - type: checkboxes
    id: device-considerations
    attributes:
      label: Which devices should this improvement consider?
      description: Check all that apply
      options:
        - label: Desktop computers
        - label: Laptops
        - label: Tablets (iPad, Android tablets)
        - label: Smartphones
        - label: School computers/Chromebooks
        - label: All devices

  - type: dropdown
    id: priority
    attributes:
      label: How important is this improvement?
      options:
        - Low - Nice to have, but not essential
        - Medium - Would make the site noticeably better
        - High - Current design causes frequent confusion or problems
        - Critical - Current design prevents people from using the site effectively
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples or inspiration
      description: Do you have examples of other websites or designs that do this well?
      placeholder: |
        Example: "The school district's main website has a really clear search box at the top"
        or "I like how the library website shows book covers - we could show activity images"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional information
      description: Any other details, constraints, or considerations?

  - type: markdown
    attributes:
      value: |
        ## For the Developer
        
        **Acceptance Criteria:**
        - [ ] The UI/UX improvement should be implemented as described
        - [ ] The change should enhance usability without breaking existing functionality
        - [ ] The improvement should work across all specified device types
        - [ ] The design should maintain visual consistency with the rest of the site
        - [ ] The change should be accessible (consider color contrast, font sizes, etc.)
        
        **Technical Implementation Notes:**
        - Primary CSS file: `/src/static/styles.css`
        - HTML structure: `/src/static/index.html`
        - JavaScript interactions: `/src/static/app.js`
        - Consider responsive design breakpoints
        - Test accessibility with screen readers if applicable
        - Ensure color choices meet WCAG contrast requirements
        - Test on multiple browsers and devices
        - Consider loading performance impact of design changes